# This file was generated by GoReleaser. DO NOT EDIT.
class SolanaGo < Formula
  desc "Cross-platform Solana command-line swiss-army-knife"
  homepage "https://dfuse.io/"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/dfuse-io/solana-go/releases/download/v0.1.0/solana-go_0.1.0_macOS_x86_64.tar.gz"
    sha256 "4e000b0ffcf963fef07119ecd84838b4138c7c3be7aa9e86f3525872b5b9df63"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/dfuse-io/solana-go/releases/download/v0.1.0/solana-go_0.1.0_linux_x86_64.tar.gz"
      sha256 "d0560d22bc17370ac8e46f9a8706956f79b8c968d56b41882d134f207256b674"
    end
  end

  def install
    bin.install "slnc"
  end
end
