# This file was generated by GoReleaser. DO NOT EDIT.
class SolanaGo < Formula
  desc "Cross-platform Solana command-line swiss-army-knife"
  homepage "https://dfuse.io/"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/dfuse-io/solana-go/releases/download/v0.1.0/solana-go_0.1.0_macOS_x86_64.tar.gz"
    sha256 "04b9576c81fa39a39d4df80cfc1ddb81f55eada200d9f4e2805002d3cc97933d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/dfuse-io/solana-go/releases/download/v0.1.0/solana-go_0.1.0_linux_x86_64.tar.gz"
      sha256 "0492a56bc02375e9b7bcca076e453d2a6ed37fd3c92bb9fea5afdbf908d7d91c"
    end
  end

  def install
    bin.install "slnc"
  end
end
